export * as TenantRouter from "./tenant.route.js"
export * as UserRouter from "./user.route.js"
export * as StreamRouter from "./stream.route.js"
export * as AgendaRouter from "./agenda.route.js"
export * as PaymentRouter from "./payment.route.js"
export * as TransactionRouter from "./transaction.route.js"
export * as PollRouter from "./poll.route.js"
export * as ParticipantRouter from "./participant.route.js"
export * as QuizRouter from "./quiz.route.js"
export * as TenantMeRouter from "./tenant-me.route.js"
export * as ProgramRouter from "./program.route.js"
export * as MonitorRouter from "./monitor.route.js"
export * as QArouter from "./qa.route.js"
export * as BalanceRouter from "./balance.route.js"
// export * as AIRouter from "./ai.route.js"
// export * as VideoProcessingRouter from "./video-processing.route.js"
// export * as SportsRouter from "./sports.route.js"
export * as WebhookRouter from "./webhook.routes.js"